---
driver:
  name: vagrant

provisioner:
  name: shell

verifier:
  name: inspec

platforms:
  - name: ubuntu-1804
    driver_config:
      box: bento/ubuntu-18.04

suites:
  - name: base
    provisioner:
      script: 'test/scripts/bootstrap.sh'
      arguments: ['core', 'httpd']
    verifier:
      inspect_tests:
        test/integration/base/inspec

