---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4.4
  - 2.5
  - 2.6
before_install:
  - gem update --remote bundler
  - gem --version
bundler_args: --without integration
script:
  - bundle exec rake lint
  - bundle exec rake test
