# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

pipelines:
 - verify:
    description: Pull Request validation tests
    public: true

slack:
 notify_channel: inspec-notify

# When we promote, which gems will we promote as part of the built_in:publish_rubygems action?
rubygems:
  - train-habitat

promote:
  actions:
    - built_in:publish_rubygems

github:
 delete_branch_on_merge: true
 minor_bump_labels:
  - "Expeditor/Bump Minor Version"
 version_tag_format: v{{version}}
 release_branch:
  - master

changelog:
 categories:
  - "Type/New Feature": "New Features"
  - "Type/Enhancement": "Enhancements"
  - "Type/Bug": "Bug Fixes"

merge_actions:
 - built_in:bump_version:
    ignore_labels:
     - "Expeditor/Skip Version Bump"
     - "Expeditor/Skip All"
 - bash:.expeditor/update_version.sh:
    only_if: built_in:bump_version
 - built_in:update_changelog:
    ignore_labels:
     - "Expeditor/Skip Changelog"
     - "Expeditor/Skip All"

